name: CI

on:
  push:
    paths:
      - 'composer.json'
      - '.github/workflows/ci.yml'
      - '**.php'
  pull_request:
    paths:
      - 'composer.json'
      - '.github/workflows/ci.yml'
      - '**.php'

jobs:
  build:
    name: Build PHP/TYPO3
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - php-versions: 7.4
            typo3-versions: ^11
          - php-versions: 8.0
            typo3-versions: ^11
          - php-versions: 8.1
            typo3-versions: ^11
          - php-versions: 8.1
            typo3-versions: ^12
          - php-versions: 8.2
            typo3-versions: ^11
          - php-versions: 8.2
            typo3-versions: ^12
          - php-versions: 8.2
            typo3-versions: ^13
          - php-versions: 8.3
            typo3-versions: ^11
          - php-versions: 8.3
            typo3-versions: ^12
          - php-versions: 8.3
            typo3-versions: ^13
          - php-versions: 8.4
            typo3-versions: ^11
          - php-versions: 8.4
            typo3-versions: ^12
          - php-versions: 8.4
            typo3-versions: ^13
    steps:
      - name: Check out repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 1
      - name: Setup PHP version
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring
      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Install composer dependencies
        run: |
          composer remove symplify/phpstan-rules --dev --no-update
          composer require typo3/cms-core=${{ matrix.typo3-versions }} --no-progress --prefer-dist --optimize-autoloader
      - name: Run PHP linter
        run: |
          find . -type f -name '*.php' ! -path "./.Build/*" -print0 | xargs -0 -n1 -P4 php -l -n | (! grep -v "No syntax errors detected" )
      - name: Run unit tests
        run: |
          make tests
  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 1
      - name: Setup PHP version
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          coverage: pcov
          extensions: mbstring
      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          restore-keys: ${{ runner.os }}-composer-
      - name: Install composer dependencies
        run: |
          composer update --no-progress --prefer-dist --optimize-autoloader
      - name: Normalize composer.json
        run: |
          composer normalize --dry-run
      - name: Check coding standards
        run: |
          .Build/bin/ecs check --no-progress-bar
      - name: Run phpstan
        run: |
          make phpstan
      - name: Run rector
        run: |
          make rector-dry
